version: '3'

vars:
  PYTHON_VERSION: 3.11.0
  PYENV_NAME: family-budget

tasks:

  run:django:
    cmds:
      - python manage.py runserver 127.0.0.1:8000

  migrate:
    cmds:
      - poetry run python manage.py migrate {{ .CLI_ARGS }}

  makemigrations:
    cmds:
      - poetry run python manage.py makemigrations {{ .CLI_ARGS }}

  collectstatic:
    cmds:
      - poetry run python manage.py collectstatic {{ .CLI_ARGS }}

  test:
    cmds:
      - poetry run pytest -svv {{ .CLI_ARGS }}

  format:ruff:
    cmds:
      - ruff check --fix-only --ignore COM819
      - ruff format

  format:
    cmds:
      - task: format:ruff

  lint:ruff:
    cmds:
      - ruff check .

  lint:
    cmds:
      - task: lint:ruff
        vars:
          LINT_MYPY_KWARGS: '{{ default "" .LINT_MYPY_KWARGS }}'