# Generated by Django 5.2 on 2025-04-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("product", "operation_datetime", "amount", "card_last_four")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["product", "operation_datetime", "amount", "card_last_four"],
                name="transaction_product_84322e_idx",
            ),
        ),
    ]
